networks:
    dspace_network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16
services:
    ctun:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_ctun:2025-07-25
        container_name: ctun
        ports:
            - 1723:1723/udp
        cap_add:
            - NET_ADMIN
            - SYS_PTRACE
        networks:
            dspace_network:
                ipv4_address: 10.6.0.8
        depends_on:
            veos:
                condition: service_started

    veos:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/combined_simphera_local_executor_246:race_2025-07-18
        container_name: veos
        cap_add:
            - SYS_PTRACE
        environment:
            - DS_CMU_SERVER=license-server-lb-37903434.eu-central-1.elb.amazonaws.com
            - DS_VEOS_LOAD_OSA=/home/dspace/VEOS/ASM_Traffic.osa
            - DS_ASM_SCENARIO_ID=1 # ID 1: IMS; ID 2: Las Vegas, ID 3: Monza start in pit, ID 4: Monza start on racetrack, ID 5: Monza no bail out, ID 6: Kennedy Space Center
            - USE_SIMPHERA=false
            - DS_START_COMMAND=deactivatepush2pass-start
            - DS_VEOS_REMOTE_CAPABLE=1
        env_file: "start_executor_env.list"
        shm_size: 256m
        networks:
            dspace_network:
                ipv4_address: 10.6.0.2
        depends_on:
            vesi:
                condition: service_started

    vesi:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_vesi:2025-07-25
        container_name: vesi
        restart: always
        tty: true
        networks:
            dspace_network:
                ipv4_address: 10.6.0.3

    dspace_bridge:
        image: dspace/iac_asm_socketcan_bridge:2025-10-01
        container_name: asm_socketcan_bridge
        # image: dspace/iac_asm_ros2_bridge:2025-10-01
        # container_name: asm_ros2_bridge
        # image: dspace/iac_aurelion_ros2_bridge:2025-10-01
        # container_name: aurelion_ros2_bridge
        # image: dspace/iac_dspace_bridge_dev:2025-10-01
        # container_name: dspace_bridge_dev
        restart: always
        cap_add:
            - SYS_ADMIN
            - DAC_READ_SEARCH
            - SYS_PTRACE
            - NET_RAW
            - NET_ADMIN
        networks:
            dspace_network:
                ipv4_address: 10.6.0.4
        depends_on:
            veos:
                condition: service_healthy

    dspace_foxglove_bridge:
        image: dspace/iac_dspace_bridge_foxglove:2025-10-01
        container_name: foxglove_bridge
        ports:
            - 8765:8765/tcp
        networks:
            dspace_network:
                ipv4_address: 10.6.0.6

    uva_example_driving_stack:
        image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_uva_demo_av_stack:2025-07-25
        container_name: driving_stack
        environment:
            - SIM_CLOCK_MODE=false
            - CAR_NUM=78
        networks:
            dspace_network:
                ipv4_address: 10.6.0.7
        depends_on:
            veos:
                condition: service_healthy
