networks:
    dspace_network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.6.0.0/16

services:
  veos:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_veos_asm_executor:sim_pack_v4.0
    container_name: veos
    cap_add:
        - SYS_PTRACE
    environment:
        - DS_CMU_SERVER=xxx
        - DS_VEOS_LOAD_OSA=/home/dspace/VEOS/ASM_Traffic.osa
        - DS_ASM_SCENARIO_ID=1 # ID 1: IMS; ID 2: Putnam Park, ID 3: Monza, ID 4: Las Vegas Outside Course, ID 5: Laguna Seca (new versions, no pit), ID 6: Laguna Seca (old versions, with pit)
        - DS_START_COMMAND=deactivatepush2pass-start
        - DS_VEOS_REMOTE_CAPABLE=1
        - DS_ROUTE_ID=2 # 1: start on track, 2: start in pit lane
        - DS_INIT_S=400 # distance around track in meters
    shm_size: 256m
    networks:
        dspace_network:
            ipv4_address: 10.6.0.2
    depends_on:
        vesi:
            condition: service_started

  vesi:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_vesi:sim_pack_v4.0
    container_name: vesi
    restart: always
    tty: true
    networks:
        dspace_network:
            ipv4_address: 10.6.0.3
    depends_on:
        can-netns:
            condition: service_started

  can-netns:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_asm_socketcan_bridge:sim_pack_v4.0
    container_name: can-netns
    ipc: "shareable"
    shm_size: "512m"
    ports:
        - 8765:8765/tcp
    cap_add:
        - NET_ADMIN
    entrypoint:
        - sh
        - -lc
        - |
            modprobe vcan 2>/dev/null || true
            ip link add dev can0 type vcan 2>/dev/null || true
            ip link add dev can1 type vcan 2>/dev/null || true
            ip link set can0 up || true
            ip link set can1 up || true
            tail -f /dev/null
    networks:
        dspace_network:
            ipv4_address: 10.6.0.4

  dspace_restbus_bridge:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_asm_socketcan_bridge:sim_pack_v4.0
    container_name: asm_socketcan_bridge
    restart: no
    volumes:
        - ./asm_socketcan_bridge_override.yaml:/root/dspace_bridge_ws/install/asm_socketcan_bridge/share/asm_socketcan_bridge/config/asm_socketcan_bridge.yaml
    cap_add:
        - NET_ADMIN
        - SYS_PTRACE
    security_opt:
        - seccomp:unconfined
    network_mode: "service:can-netns"
    ipc: "container:can-netns"
    depends_on:
        veos:
            condition: service_healthy
        can-netns:
            condition: service_started

  dspace_foxglove_bridge:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_ros2_foxglove_bridge:sim_pack_v4.0
    container_name: foxglove_bridge
    network_mode: "service:can-netns"
    ipc: "container:can-netns"
    depends_on:
        veos:
            condition: service_healthy
        can-netns:
            condition: service_started

  lichtblick_local:
    image: ghcr.io/lichtblick-suite/lichtblick:latest
    container_name: lichtblick_local
    ports:
      - 8080:8080
    networks:
      dspace_network:
        ipv4_address: 10.6.0.9

  demo_stack_uva:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_uva_demo_av_stack:sim_pack_v4.0
    container_name: demo_stack_uva
    environment:
        - SIM_CLOCK_MODE=false
        - CAR_NUM=78
    volumes:
        - ./demo_stack_uva/ims.param_override.yaml:/root/ros_ws/src/npc_controller/config/ims.param.yaml
    network_mode: "service:can-netns"
    ipc: "container:can-netns"
    depends_on:
      veos:
        condition: service_healthy
      can-netns:
        condition: service_started

  raptor_dbw:
    image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_socketcan_dbw_bridge:sim_pack_v4.0
    container_name: raptor_dbw
    restart: no
    cap_add:
        - NET_ADMIN
    network_mode: "service:can-netns"
    ipc: "container:can-netns"
    depends_on:
        veos:
            condition: service_healthy
        can-netns:
            condition: service_started

#   ctun:
#     image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_ctun:sim_pack_v4.0
#     container_name: ctun
#     ports:
#         - 1723:1723/udp
#     cap_add:
#         - NET_ADMIN
#         - SYS_PTRACE
#     networks:
#         dspace_network:
#             ipv4_address: 10.6.0.8
#     depends_on:
#         veos:
#             condition: service_started

# Example for adding a sensor bridge for sensor simulation with AURELION
    # dspace_sensor_bridge:
    #     image: 722180079256.dkr.ecr.eu-central-1.amazonaws.com/dspace/iac_aurelion_ros2_bridge:2026-05-06
    #     container_name: aurelion_ros2_bridge
    #     restart: always
    #     environment:
    #         - VESI_SENSOR_IP=
    #         - VESI_SENSOR_PORT=12345
    #         - SENSOR_TYPE=Lidar
    #         - SENSOR_ID=1
    #         - ROS_TOPIC=lidar_front
    #     cap_add:
    #         - SYS_ADMIN
    #         - DAC_READ_SEARCH
    #         - SYS_PTRACE
    #     networks:
    #         mynetwork:
    #             ipv4_address: 10.6.0.10
