#!/bin/bash
source /opt/ros/humble/local_setup.bash
source /root/ros_ws_aux/install/local_setup.sh
source /root/dspace_bridge_ws/install/local_setup.bash
ros2 run asm_socketcan_bridge AsmSocketCanBridgeNode