#!/bin/bash
source /opt/ros/$ROS_DISTRO/local_setup.bash
source /root/ros_ws_aux/install/local_setup.sh
source /root/dspace_bridge_ws/install/local_setup.bash
ros2 run aurelion_ros2_bridge AurelionRos2BridgeNode