#!/bin/bash
source /opt/ros/kilted/local_setup.bash
source /root/ros_ws_aux/install/local_setup.sh
source /root/ros_dbw_ws/install/local_setup.sh
cd /root/ros_dbw_ws/
ros2 launch raptor_dbw_can raptor_dbw_can_launch_entire.py