#!/bin/bash
source /opt/ros/humble/local_setup.sh
# source /root/ros_ws_aux/install/local_setup.sh
rosdep install -i --from-path /root/ros_ws_aux/src --rosdistro humble -y
colcon build --symlink-install --cmake-clean-first --base-paths /root/ros_ws_aux/ --build-base /root/ros_ws_aux/build --install-base /root/ros_ws_aux/install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo 
